apiVersion: v1
kind: Service
metadata:
  name: segmentation-service
spec:
  type: LoadBalancer
  selector:
    app: segmentation-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
